default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: Ruby-on-Rails-Hotwire---SPA_development

test:
  <<: *default
  database: Ruby-on-Rails-Hotwire---SPA_test

production:
  <<: *default
  database: Ruby-on-Rails-Hotwire---SPA_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
